name: "Snyk SCA - Dependency Analysis"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects --json-file-output=snyk-results.json

    - name: Upload Snyk results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-results
        path: snyk-results.json

    - name: Run Snyk test and generate report
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        npm install -g snyk
        snyk auth $SNYK_TOKEN
        snyk test --json > snyk-report.json || true
        snyk test --sarif > snyk-report.sarif || true

    - name: Upload Snyk JSON report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-json-report
        path: snyk-report.json

    - name: Upload Snyk SARIF report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-sarif-report
        path: snyk-report.sarif

    - name: Generate Snyk HTML Report
      if: always()
      continue-on-error: true
      run: |
        npm install -g snyk-to-html
        snyk-to-html -i snyk-report.json -o snyk-report.html || echo "HTML generation completed"

    - name: Upload Snyk HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-html-report
        path: snyk-report.html